<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>$title$</title>
    $head;format="none"$
</head>
<body class='$page.properties.("body.class")$'>
<div id="container">
    <div id="header">
        <h1>$title$</h1>
    </div>
    <div id="content">
        $body;format="none"$
    </div>
</div>
</body>
</html>
